name: Run and Push Script

permissions:
  contents: read
  pages: write

on: 
  schedule:
    - cron: '* * * * *'  # Runs every 6 hours
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Choose the Python version you need
          
      - name: Install dependencies
        run: pip install -r requirements.txt  # Install any Python dependencies if needed
        
      - name: Run script
        run: |
          python -m pip install --upgrade pip
          pip install jupyter
          jupyter nbconvert --to script Movie_scraping.ipynb  # Run your Python script
        
      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Update JSON file"
          git push https://github.com/Syed-Abdullah-G/moviescraper.git HEAD:master
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
